apiVersion: v1
kind: Namespace
metadata:
  name: dev-devci
---
apiVersion: v1
kind: Service
metadata:
  name: exposed-webapi-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: webapi
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/name: webapi
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
  namespace: dev-devci
  labels:
    app.kubernetes.io/name: webapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: webapi
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapi
    spec:
      containers:
        - name: webapi
          image: "courseswebapi:dev"
          imagePullPolicy: IfNotPresent
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /probe/live
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          resources:
            limits:
             cpu: 100m
             memory: 128Mi
            requests:
             cpu: 100m
             memory: 128Mi